### ISSUE TITLE
有个文件看不懂

### ISSUE THREAD

**Issue by prlei** [Tmfree/vue-fiction#12]
hi 兄弟
const crawRouter = require('./router/craw')
这个我怎么也没有检索出来，是我错过了什么嘛？

`⇒  node app.js
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module './router/craw'
Require stack:
- /xxxxxxxx/vue-fiction/server/app.js`

**Comment by Tmfree** [comment]
注释掉就可以

**Comment by prlei** [comment]
我重新 clone 了项目，什么都没有修改，直接 yarn install

出现

114:13 Cannot find name 'home_index'.
    112 |           hotfiction,
    113 |           bestsellfiction,
  > 114 |         } = home_index;
        |             ^
    115 |         this.lunboList = banner;
    116 |         this.newFictionList = newfiction;
    117 |         this.qingFictionList = qingfiction;
Version: typescript 3.8.3
Time: 3310ms

  App running at:
  - Local:   http://localhost:8080/
  - Network: http://192.168.8.114:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

**Comment by Tmfree** [comment]
这个是后台直接请求一个js文件，全局变量问题，你可以自己处理请求
